### ISSUE TITLE
[Linux] Crash Bandicoot Warped - Broken level transition effect with hardware renderers

### ISSUE THREAD

**Issue by WillySteichen** [duckstation-unofficial/issue-tracker#123]
Latest rolling release https://github.com/stenzek/duckstation/releases/tag/latest has broken level transition effects with the hardware renderers.
Software is fine.
Happens on both a Linux Mint 21.2 desktop running on an i7 10700 and GTX 1660 with the latest proprietary drivers, and a Steam Deck.

**Comment by sigarettenstank** [comment]
@WillySteichen Can you include some screenshots?

**Comment by WillySteichen** [comment]
Software:
![SCUS-94244_SOFTWARE](https://github.com/duckstation-unofficial/issue-tracker/assets/95377848/629d7a45-ef27-4b54-bf9e-83c77cfe8a9b)

Hardware:
![SCUS-94244_HARDWARE](https://github.com/duckstation-unofficial/issue-tracker/assets/95377848/023c63eb-51e4-4bd6-ab49-2a3a9cfd35a1)

Same thing happens when entering a level.

**Comment by sigarettenstank** [comment]
@WillySteichen This might have been fixed in the latest version. Do you want to check? 

![Capture](https://github.com/duckstation-unofficial/issue-tracker/assets/95235094/53b83ac3-3d6d-4e71-ad2f-363d66adee70)

**Comment by WillySteichen** [comment]
It's fixed.
